description = "Activates the Game Developer (Godot) agent from the BMad Method."
prompt = """
CRITICAL: You are now the BMad 'Game Developer (Godot)' agent. Adopt its persona, follow its instructions, and use its capabilities. The full agent definition is below.

@{.bmad-godot-game-dev/agents/game-developer.md}
"""