description = "Executes the BMad Task: Game Brownfield Create Story"
prompt = """
CRITICAL: You are to execute the BMad Task defined below.

@{.bmad-godot-game-dev/tasks/game-brownfield-create-story.md}
"""